services:

  parking_service:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - parking_db
      - rabbitmq
    env_file:
      - .env

  worker:
    build: .
    command: celery -A core worker -l INFO
    restart: always
    depends_on:
      - parking_db
      - rabbitmq
    env_file:
      - .env

  parking_db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:4.0-management
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    env_file:
      - .env